spring.application.name=spring-jwt

# logging ?? ??
logging:
    level:
        root: INFO
        sql: ERROR
# Overloaded POST ??
spring:
    mvc:
        hiddenmethod:
        filter:
            enabled: true

jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

