# logging ?? ??
logging:
    level:
        root: INFO
        sql: ERROR
# Overloaded POST ??
spring:
    mvc:
        hiddenmethod:
            filter:
                enabled: true
jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
    access:
        expiration: 30000 # 1??(60?) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
        header: Authorization

    refresh:
        expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> ??) * 14(2?))
        header: Authorization-refresh